# This workflow will install Python dependencies and run mypy

name: Mypy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: [3.9, "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Run mypy
      run: |
        mypy --strict .
